### ISSUE TITLE
Doesn't work with last Discord update (1.0.9001)

### ISSUE THREAD

**Issue by barbaduk** [BetterDiscord/Installer#106]
BD is in infinity loading state.
I completely deleted Discord and BD with all folders in appdata.
Then i installed discord, restarted it couple of times so it would update to 1.0.9001 and then installed last BD release (zero themes or plugins, 100% default).
And yeah, i tried disabling Emotes and everything else and restarting and waiting for hours to let it load.
It just doesn't work and doesn't load plugins (of course) if i add them.

![BDdw](https://user-images.githubusercontent.com/41954202/114463163-bf5c0c80-9bec-11eb-817b-0d7dbd5f8686.jpg)

**Comment by Tropix126** [comment]
BD appears to have loaded, but the settings sidebar is broken. This is a known issue with the client, and will be fixed in the next update (BD 1.1.0). You can inject BD 1.1.0 now before the release by following these [instructions](https://github.com/rauenzi/betterdiscordapp#manual-installation). Either way, this isn't inherently related to the installer.
