### ISSUE TITLE
Installer stalls at "Downloading asar file" on Ubuntu 20.04

### ISSUE THREAD

**Issue by CheatCod** [BetterDiscord/Installer#137]
**Describe the bug**
The installer is stuck on "Downloading asar file" on Ubuntu Linux 20.04

**To Reproduce**
1. Mark the latest downloaded AppImage as executable 
2. Execute the AppImage
3. Go through the installation
4. Installer stalls at "Downloading asar file"

**Expected behavior**
A successful installation 

**Screenshots**
![image](https://user-images.githubusercontent.com/47200772/119594935-b3966500-bdaa-11eb-8cf0-f07c61e00266.png)

**System Information:**
 - OS: Ubuntu 20.04

**Additional Info**
I have tried disabling Ubuntu's firewall to no avail, the same installer works on the same PC on windows (I have a dual boot setup)

**Comment by CheatCod** [comment]
I'm still unsure of the origin of the bug, but I fixed it by replacing the line
`downloadUrl = asset.url;`
with
`downloadUrl = "https://github.com/rauenzi/BetterDiscordApp/releases/download/v1.1.1/betterdiscord.asar";`
under 
installer/src/renderer/actions/install.js 

and running script 
`npm run dev`

**Comment by shiypc** [comment]
Since this bug is pretty new, I compiled the installer with the fix in place. I had to use macOS to compile since Ubuntu wouldn't, so for anyone else having problems fixing it, [here's the fixed installer](https://drive.google.com/file/d/1y9oMOpj3VdhMTXns96ttJ8kRsd6m3KKn/view?usp=sharing). If anyone has problems installing, let me know.
