### ISSUE TITLE
Visible Version Information

### ISSUE THREAD

**Issue by Inve1951** [BetterDiscord/Installer#236]
**Is your feature request related to a problem? Please describe.**
Currently the installer UI has no indicator which BD version is to be installed.

**Describe the solution you'd like**
Display detected installed and remote version numbers of BD. We could additionally put the installer version in the title bar or footer to identify it on screenshots.
Could go as far as fetching the remote version, comparing it to local, and presenting the user with an ***Update Existing Installation(s)*** thing after license acceptance, if one is found and a newer version is available.

**Describe alternatives you've considered**
At least log the version that got installed.

Btw, I think this [temporary workaround](https://github.com/BetterDiscord/Installer/blob/e6fa2a10756c536f69775db3a8d70888330afa7c/src/renderer/actions/install.js#L85) can go. Can only guess it was related to rate limiting which should no longer be an issue.

**Comment by QbDesu** [comment]
Ah, the temporary workaround can go yeah, it was a workaround for when the installer broke when the repo was moved to the BD organization and we didn't realize it was because of it (and the installer wasn't following redirects yet), so we thought it was a github issue at the time.

But yeah might be nice to see version information. ~~But how would we go about detecting the version that is installed locally?~~ Nevermind, it's in the misc.json in the release branch's data folder.
