### ISSUE TITLE
Can't locate Discord PTB

### ISSUE THREAD

**Issue by PedroAlves24** [BetterDiscord/Installer#276]
**Description**
I installed Discord Portable via [Scoop](https://scoop.sh/) and when I try to install Better Discord and point it to my DiscordPTB installation in `<SCOOP_PATH>/apps/discord/current/` (where `discord-portable.exe` is located) it keeps saying `Not Found`.

**To Reproduce**
1. (Optional) `$ scoop bucket add extras`
2. `$ scoop install discord`
3. Open Better Discord Installer
4. Click `Browse` in order to locate Discord PTB
5. Choose `<SCOOP_PATH>/apps/discord/current/` or `<SCOOP_PATH>/apps/discord/current/app/app-X.X.X/`
6. Nothing happens. It keeps saying `Not found`

**Expected behavior**
It should find my Discord installation and allow me to proceed with the installation.

**System Information:**
- OS: Windows
- Discord Version: Portable

**Comment by mokocup** [comment]
There is two problem i see here make this not a bug but unsupported instead/

1. Your Discord version is portable , it might use different AppData folder path (%localappdata%\Discord) so you need check it out first since BetterDiscord Installer only support that path.
2. https://github.com/BetterDiscord/Installer/blob/e2782c4395269ca72098ddee6205361ccf7ebb4a/src/renderer/actions/install.js#L25-L28
3. Look at your folder structure , the installer wont work because it have /current/ directory. Maybe you should try <SCOOP_PATH>/apps/discord/current/app instead . References in this
https://github.com/BetterDiscord/Installer/blob/e2782c4395269ca72098ddee6205361ccf7ebb4a/src/renderer/actions/paths.js#L49-L70

Might be workaround for you is #217
