### ISSUE TITLE
[Suggestion] Rename "Repair" to "Reset" and delete plugins.json and themes.json

### ISSUE THREAD

**Issue by fowlis** [BetterDiscord/Installer#284]
**Is your feature request related to a problem? Please describe.**
I find that *a lot* of people seem to think repairing BD through the installer will fix their plugin/theme issues, obviously it can't but maybe resetting BD to a state where nothing is enabled with the repair option would be a good idea

Not sure if this is already in the pipeline or has been considered but rejected before

**Describe the solution you'd like**
Rename "Repair" to "Reset" and make it delete the plugins.json and themes.json files (and maybe settings.json)
Alternatively, rename the current plugins and themes folders to "pluginsOld" and "themesOld" respectively and create new empty ones

It would probably need an extra confirmation screen just to tell users that:
a. it won't actually delete their plugins/themes and is just "moving" them to a different location they can move them back from
b. it won't fix 99% of issues they think resetting BD will fix

**Describe alternatives you've considered**
None I can think of

**Comment by Arcitec** [comment]
I'll just explain exactly what the current "Repair" option does:

- It keeps your BetterDiscord config folder (with the ASAR file and all your configs etc).
- It deletes Discord's latest version data, so that Discord will re-download its own latest update when you start it again.
- It disables BetterDiscord by removing it from Discord's loading scripts/folders.

After doing the repair, you'll have a clean Discord without any BD enabled. Then the BetterDiscord installer asks if you want to re-install BetterDiscord. If you do, it grabs the latest BetterDiscord ASAR file and re-adds BD to Discord's loading process.

My guess is that the intent behind the feature is to give users a "oh shit" button if Discord is unable to start due to conflicts between BetterDiscord and Discord, or bugs in the currently installed Discord code, etc. And the ability to say "No, don't install BD again" may be intended as a failsafe if users are unable to start Discord with BD enabled.

The feature is actually very similar to the "Uninstall" option, except that uninstalling only removes BD from the loading scripts. The "repair" removes BD from the loader AND cleans Discord's own files, which means a deeper cleanup than "uninstall".

Wiping actual BetterDiscord settings would be very invasive, and people are generally pretty lazy and don't read dialogs, so they may click "Yes" on a dialog without knowing what they're doing. Tons of people are really dumb (shocking, I know), and just click Yes Yes Yes Yes without reading a single word. Those people are the reasons for warning labels such as "don't hold the wrong end of the chainsaw": https://www.youtube.com/watch?v=-9Q0ZLsJcXE

Deleting the BetterDiscord settings rarely solves anything anyway, and people can do it manually if there's ever a reason to do so. If you can think of a convincing reason to delete settings, and what it **solves,** that would help evaluate this idea. :D

If it's just a desire to "go back to default settings", then that would be better suited as a button/feature inside BetterDiscord itself, not in the installer.

Even the ability to unload the current CSS theme would be better suited as a feature in BetterDiscord itself. Something like "hold shift-F10 while starting Discord to prevent BD from loading the CSS theme", would be a better way to solve CSS issues.

**Comment by fowlis** [comment]
Hi, thanks for your response ♥
I should have put more thought and a bit of research into this, it was mainly just an idea I had that I thought to share
I guess the option is quite misleading for those users who expect it to fix their problems, since I find a lot of people who say they tried repairing BD to fix some issue they were having with plugins
> people are generally pretty lazy and don't read dialogs

I do agree that there are loads of people who will just skip reading important information and then be confused why something happened, its unfortunately a common problem in the support server - where there are listed solutions to the most common issues and people will somehow be entirely blind to them

> If it's just a desire to "go back to default settings", then that would be better suited as a button/feature inside BetterDiscord itself, not in the installer.

I quite like this idea honestly, miles better than what I was thinking here. I know there's a "safe-mode" in the works for BD, but I'm not sure if that's mainly for when it crashes. Or perhaps if there will also be a button/maybe even shortcut in-app you can press to activate the safe mode, which would be neat 🤔

> Even the ability to unload the current CSS theme would be better suited as a feature in BetterDiscord itself. Something like "hold shift-F10 while starting Discord to prevent BD from loading the CSS theme", would be a better way to solve CSS issues.

I'm not sure how something like this would work, I've been led to believe that BD doesn't load until Discord is ready. Maybe I'm wrong and this is a possibility? Though I feel like it would be something that's easy to miss depending on how quick the user's Discord loads

Apologies for not thinking that much about the idea and posting an issue so quick after it popped into my head, I'll close this now 👋
