### ISSUE TITLE
Installer gets stuck on "Attempting to kill Discord"

### ISSUE THREAD

**Issue by Vulpovile** [BetterDiscord/Installer#287]
**Describe the bug**
Installer gets stuck on Attempting to kill Discord once started, even if discord is already killed

**To Reproduce**
1. Run Installer
2. Click on Install
3. Select discord

**Expected behavior**
The installer should proceed without issue, especially when discord is not even running

**System Information:**
 - OS: Windows 7 64 bit (With ESU)
 - Discord Version: Stable

**Comment by Vulpovile** [comment]
![image](https://user-images.githubusercontent.com/19483545/197347883-6575e6e4-bc0a-4317-9b62-b621a9519a44.png)

**Comment by Ximerixx** [comment]
Same for me, in any situations, installing or repairing Discord
One-time solution for this is kill powershell script, but that's won't work if you repair it

I think problen is in `powershell.exe /c "Get-CimInstance -className win32_process | select Name,ProcessId,ParentProcessId,CommandLine,ExecutablePath"`command which don't work on Win7 cuz it don't have that commndlet

Creators should propably fix that...

**Comment by Inve1951** [comment]
The way the process is killed changed in this installer release (v1.1.2). This is due to Win11 having dropped the "wmic" tool which was part of previous windows releases and thus the same issue would happen there without this change. Win7, while a great OS, has reached end of life  as you should be aware. As a consequence more and more software vendors drop support too.
Maybe we can get this addressed upstream: https://github.com/yibn2008/find-process/issues/54
As a workaround you can use the v1.1.1 installer and dismiss the update notice or manually kill all discord instances.

**Comment by jacobwatkinsgit** [comment]
Getting the same bug. FindProcess should've used taskkill which has the one job of listing processes and killing them, instead of the complete management 'interface'.

Can the issue be solved in: https://github.com/BetterDiscord/Installer/blob/fa31f1a177ee41067666470dba2f8d4aa8a8a33b/src/renderer/actions/utils/kill.js

I'm not a javascript programmer, but there's clearly an issue with code starting line 17:

https://github.com/BetterDiscord/Installer/blob/fa31f1a177ee41067666470dba2f8d4aa8a8a33b/src/renderer/actions/utils/kill.js#L17

Discord isn't running. I don't have the environment to test what's going on at the moment, but this should not be succeeding. If FindProcess isn't reporting an error for not being able to run it's Powershell scripts, that's not being communicated properly. There's clearly no timeout, so could that be added? If, for any reason, the find/kill process fails, it doesn't seem right to lock up the application.

**Comment by Ximerixx** [comment]
> The way the process is killed changed in this installer release (v1.1.2). This is due to Win11 having dropped the "wmic" tool which was part of previous windows releases and thus the same issue would happen there without this change. Win7, while a great OS, has reached end of life  as you should be aware. As a consequence more and more software vendors drop support too.
> Maybe we can get this addressed upstream: https://github.com/yibn2008/find-process/issues/54
> As a workaround you can use the v1.1.1 installer and dismiss the update notice or manually kill all discord instances.


Yes, it's definitely a good one (that's why I'm using it, but there's no real reason to drop support for it
At least 1.1.1 works whenever is is installed above 7, and I don't know why you broke what was working

**Comment by Inve1951** [comment]
> Yes, it's definitely a good one (that's why I'm using it, but there's no real reason to drop support for it
At least 1.1.1 works whenever is is installed above 7, and I don't know why you broke what was working

absolutely agree. This breaking change was not intended from our side and there's no plans to drop support for win7 at this time. which is also why i didn't close this issue as 'wont-fix'.
the new find-process version closed the issue with win11 and no testing for win7 was done then apparently.

**Comment by hooddy** [comment]
v1.1.2 stil wont works trhough installation proccess at Win7.

**Comment by ccrowles** [comment]
Same issue for me, on Windows 10.
Discord just got updated and when I attempted to reinstall BD it gets stuck at attempting to kill the process.

**Comment by Paft** [comment]
I can't install it either. I've often had this issue and then forget how to fix it when it happens again..

Win 11 21H2.

What I've tried:
-Deleting _C:\Users\Administrator\AppData\Local\Discord_ and reinstalling Discord.
-Adding _C:\Windows\System32_ to Environment Variables 'Path'.
-Running as Admin.

Edit: Installed 1.1.1 https://github.com/BetterDiscord/Installer/releases/tag/v1.1.1

**Comment by Vulpovile** [comment]
This is still happening.

**Comment by Paft** [comment]
Yeah, still a problem. I have to keep installing 1.1.1 when BD randomly decides not to be launching with Discord.

**Comment by ChaoticHolon** [comment]
This wasn't happening for me before on previous installers, but it's definitely happening now (on Windows 10 LTSC).

**Comment by slacksystem** [comment]
Came here to report this issue. Found it's been a known issue for a month. On windows 11 here discord is closed before I run the installer and it still gets stuck on that step.  Doing "repair", haven't tried "install" because I don't know if it would wipe my settings/plugins.

**Comment by Paft** [comment]
So is there no dev input on this? Even a fresh install doesn't seem to work. 1.1.1 doesn't seem to be working now. The installer finishes, but my Discord is still default.

**Comment by zerebos** [comment]
This is a problem with one of our dependencies on Windows 7, we are looking into workarounds.

**Comment by trollollol123** [comment]
Killing Discord...
Attempting to kill Discord

Windows 11 latest
Even if I kill discord before I start it still gets stuck.
