### ISSUE TITLE
New Installer Stuck on Downloading asar file.

### ISSUE THREAD

**Issue by ItsAlveolarZ** [BetterDiscord/Installer#35]
I try to install the newest installer, But the installer is keep stucking on Downloading asar file and never continues.

![image](https://user-images.githubusercontent.com/81840359/113465692-66f47480-9460-11eb-8dda-3b589c85cfe0.png)

**Comment by Tropix126** [comment]
Hi, since not much information is available here, these are a few things to attempt.

- Temporarily disable any antivirus software for the duration of the installation.
- Some firewalls have also been known to cause these issues. Try disabling those too.
- Ensure you have a stable, unrestricted internet connection

**Comment by ItsAlveolarZ** [comment]
> Hi, since not much information is available here, these are a few things to attempt.
> 
> * Temporarily disable any antivirus software for the duration of the installation.
> * Some firewalls have also been known to cause these issues. Try disabling those too.
> * Ensure you have a stable, unrestricted internet connection

Thank you very much for your help!
Disabled firewalls and antivirus works for me!

**Comment by NiiRubra** [comment]
Hello, I'm having this exact issue, there are no anti-virus or firewalls in the way, connection is fine, Discord is up to date, the problem persists. This computer is on Windows 7 32 bit.
