### ISSUE TITLE
Some themes from previous version do not work

### ISSUE THREAD

**Issue by Yxttuwu** [BetterDiscord/Installer#45]
**Describe the bug**
when applying themes from the previous version, some of them dont change anything allthough they did in the other version

**To Reproduce**
1. Go to 'settings'
2. Click on 'themes'
3. Scroll down to any theme from the previous version

**Expected behavior**
nothing changes and stays the same from when you applied the theme

**Screenshots**
![image](https://user-images.githubusercontent.com/81854177/113474209-7e366080-9466-11eb-94d6-7870507f468d.png)

**System Information:**
 - OS: Windows 10 Pro
- Discord Version: Stable (newest release) (developer mode ON)

**Additional context**
the theme code:
![image](https://user-images.githubusercontent.com/81854177/113474243-db321680-9466-11eb-94ee-bb797c17fa5d.png)

**Comment by menonsid2003** [comment]
Same issue here, also with the Spectra's theme editor theme

**Comment by rauenzi** [comment]
Themes not working are the fault of the themes or BD. Either way it is not the fault of the installer.

**Comment by dav1312** [comment]
First of all, **this is not an issue about the installer**

This is due to the fact that your theme is using and **old style of meta that is not supported anymore**
```css
//META{"name":"Name of the Theme","description": . . .
```
Replace it with this new style. More info about the new meta [here](https://github.com/rauenzi/BetterDiscordApp/wiki/Plugin-and-Theme-METAs)
```css
/**
 * @name Name of the Theme
 * @author Author of the Theme
 * @description Description of the Theme
 * @version 1.0.0
 */
```

**If** after doing the change above the theme **still doesn't work it might** also **be using normalized classes**.
Try enabling that setting in your BetterDiscord Settings > General > Normalize Classes
